USE [master]
GO

/****** Object:  Database [LocationsApi]    Script Date: 4/04/2023 9:54:07 p. m. ******/
CREATE DATABASE [LocationsApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LocationsApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LocationsApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LocationsApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LocationsApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LocationsApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LocationsApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LocationsApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LocationsApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LocationsApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LocationsApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [LocationsApi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LocationsApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LocationsApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LocationsApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LocationsApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LocationsApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LocationsApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LocationsApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LocationsApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LocationsApi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LocationsApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LocationsApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LocationsApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LocationsApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LocationsApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LocationsApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LocationsApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LocationsApi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LocationsApi] SET  MULTI_USER 
GO

ALTER DATABASE [LocationsApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LocationsApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LocationsApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LocationsApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LocationsApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LocationsApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LocationsApi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LocationsApi] SET  READ_WRITE 
GO


