INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','06:30','20:00','Horario Normal',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','06:30','20:00','Horario Normal',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','06:30','20:00','Horario Normal',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','06:30','20:00','Horario Normal',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','06:30','22:00','Horario Extendido',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','10:30','23:00','Horario Fin de Semana',2)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','06:30','23:00','Fin de Semana',2)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','10:30','18:00','Horario Normal',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','10:30','18:00','Horario Normal',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','10:30','18:00','Horario Normal',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','10:30','18:00','Horario Normal',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','10:30','18:00','Horario Normal',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','08:30','20:00','Horario Fin de Semana',3)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','08:30','20:00','Fin de Semana',3)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','11:30','19:00','Horario Normal',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','11:30','19:00','Horario Normal',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','11:30','19:00','Horario Normal',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','11:30','19:00','Horario Normal',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','11:30','19:00','Horario Normal',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','11:30','17:00','Horario Fin de Semana',5)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','11:30','17:00','Horario Fin de Semana',5)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','07:30','19:00','Horario Normal',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','07:30','19:00','Horario Normal',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','07:30','19:00','Horario Normal',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','07:30','19:00','Horario Normal',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','07:30','19:00','Horario Normal',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','09:30','12:00','Horario Fin de Semana',6)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','09:30','12:00','Horario Fin de Semana',6)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','06:30','18:00','Horario Normal',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','06:30','18:00','Horario Normal',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','06:30','18:00','Horario Normal',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','06:30','18:00','Horario Normal',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','06:30','18:00','Horario Normal',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','07:30','12:00','Horario Fin de Semana',7)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','08:30','12:00','Horario Fin de Semana',7)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','10:00','18:00','Horario Normal',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','10:00','18:00','Horario Normal',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','10:00','18:00','Horario Normal',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','10:00','18:00','Horario Normal',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','10:00','18:00','Horario Normal',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','10:00','15:00','Horario Fin de Semana',8)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','10:00','15:00','Horario Fin de Semana',8)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','08:00','18:00','Horario Normal',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','08:00','18:00','Horario Normal',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','08:00','18:00','Horario Normal',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','08:00','18:00','Horario Normal',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','08:00','18:00','Horario Normal',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','08:00','14:00','Horario Fin de Semana',9)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','08:00','14:00','Horario Fin de Semana',9)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','16:00','23:00','Horario Normal',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','16:00','23:00','Horario Normal',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','16:00','23:00','Horario Normal',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','16:00','23:00','Horario Normal',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','12:00','23:00','Horario Extendido',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','12:00','23:00','Horario Fin de Semana',10)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','12:00','23:00','Horario Fin de Semana',10)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','08:00','20:00','Horario Normal',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','08:00','20:00','Horario Normal',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','08:00','20:00','Horario Normal',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','08:00','20:00','Horario Normal',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','08:00','20:00','Horario Extendido',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','08:00','12:00','Horario Fin de Semana',11)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','08:00','12:00','Horario Fin de Semana',11)

INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Monday','14:00','22:00','Horario Normal',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Tuesday','14:00','22:00','Horario Normal',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Wednesday','14:00','22:00','Horario Normal',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Thursday','14:00','22:00','Horario Normal',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Friday','14:00','23:00','Horario Extendido',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Saturday','14:00','23:00','Horario Extendido',12)
INSERT INTO [dbo].[Schedules] ([Day],[Open],[Close],[Observation],[LocationId]) VALUES ('Sunday','14:00','20:00','Horario Domingo',12)


